version: "3.8"

services:
  documentapp-dev-container:
    container_name: documentapp-dev-container
    build:
      context: .
      dockerfile: ./backend/.devcontainer/Dockerfile
    volumes:
      - ./backend/:/workspace:cached
    command: sleep infinity
    networks:
      - dev-network
  api-gateway:
    container_name: api-gateway
    build:
      context: ./backend/api-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - JWT_SECRET=123456
      - JWT_EXPIRES_IN=1h
    networks:
      - dev-network
    depends_on:
      document-service:
        condition: service_healthy

  document-service:
    build:
      context: ./backend/document-service
      dockerfile: Dockerfile
    ports:
      - "3006:3006"
      - "4001:4001"
    environment:
      - NODE_ENV=development
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      
    healthcheck:
      test: ["CMD", "curl", "-f", "http://document-service:3006/health"]
      interval: 10s
      retries: 5
      start_period: 5s
    volumes:
      - uploads_data:/app/uploads
    networks:
      - dev-network
    depends_on:
      - postgres
      - consul
    deploy:
      replicas: 1 # Run 3 instances of Post Service
    restart: always
  consul:
    image: consul:1.14.0  # Specify a specific version
    container_name: consul
    ports:
      - "8500:8500"  # Expose port 8500 for the UI
    environment:
      CONSUL_BIND_INTERFACE: eth0
    command: "consul agent -dev -client=0.0.0.0 -bind=0.0.0.0"
    networks:
      - dev-network
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - API_URL=http://localhost:3000
      - API_PREFIX=/api
      - GOOGLE_CLIENT_ID=1017930346997-tifltb4soguftq2tap5a462si3c0krh6.apps.googleusercontent.com
      - GOOGLE_CALLBACK_URL=http://localhost:4200/auth/callback
    ports:
      - "4200:80"
    depends_on:
      - api-gateway
    networks:
      - dev-network
  auth-service:
    build: 
      context: ./backend/auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "3003:3003"
      - "3004:3004"
    environment:
      - NODE_ENV=development
      - CONSUL_HOST=consul
      - GOOGLE_CLIENT_ID=1017930346997-tifltb4soguftq2tap5a462si3c0krh6.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - GOOGLE_CALLBACK_URL=http://localhost:4200/auth/callback
      - JWT_SECRET=123456
      - JWT_EXPIRES_IN=1h
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/auth_db?schema=public
    depends_on:
      - consul
      - postgres
    networks:
      - dev-network
  postgres:
    image: postgres:16
    container_name: auth_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev-network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - dev-network

volumes:
  # mongo1_data:
  postgres_data:
  uploads_data:

networks:
  dev-network:
    driver: bridge
